import slider_img_1 from "../assets/images/slider-img-1.png";
import slider_img_2 from "../assets/images/slider-img-2.png";
import slider_img_3 from "../assets/images/slider-img-3.png";
import slider_img_4 from "../assets/images/banner.webp";
import spinner from "../assets/images/spinner.svg";
import NotFoundPage from "../assets/images/NotFoundPage.jpg";
import error from "../assets/images/error.jpg";
import emtycart from "../assets/images/emtycart.jpg";
const sliderImages =  [slider_img_1, slider_img_2, slider_img_3, slider_img_4];
export {sliderImages, spinner,error ,NotFoundPage,emtycart};